import Head from "next/head";

import DesignCard from "../../components/DesignSection/DesignCard";
import { useState } from "react";

export const getStaticProps = async () => {
  // get the response from api
  const res = await fetch(`${process.env.LOCAL_URL}/api/designs`);
  // convert the res to json
  const data = await res.json();
  // return the json data
  return {
    props: { data },
  };
};
const DesignIndex = ({ data: designs }) => {
  // FILTER:
  // put the data inside an useState to make the designs dynamic
  const [modal, setModal] = useState(null);

  return (
    <>
      <Head>
        <title>Designs - Jose Maria Ipio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative max-w-screen-lg mx-auto overflow-hidden dark:text-light">
        {/* headings */}
        <div
          className="pb-8 text-6xl font-bold dark:text-light text-dark"
          //   for the nav
          style={{ paddingTop: "96px" }}
        >
          Designs
        </div>
        {/* header */}
        <div className="">
          {/* Grid */}
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {designs.map((design) => (
              <div className="relative" key={design.id}>
                <DesignCard
                  designs={designs}
                  design={design}
                  modal={modal}
                  setModal={setModal}
                />
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export default DesignIndex;
//   const [designs, setDesigns] = useState([]);

//   const fetchDesigns = async () => {
//     const res = await fetch("/api/designs");
//     const data = await res.json();

//     setDesigns(data);
//   };
