import Head from "next/head";
import Header from "../components/Header";
import Design from "../components/DesignSection/Design";
import Project from "../components/ProjectSection/Project";
import About from "../components/AboutSection/About";
import Contact from "../components/ContactSection/Contact";

export default function Home() {
  // console.log(designs);
  // console.log(projects);
  // console.log(service);
  // console.log(tech_stacks);

  return (
    <>
      <Head>
        <title>Jose Maria Ipio | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        className="flex items-center justify-center max-w-screen-lg mx-auto md:justify-start"
        // minus navbar size: h-24 || 96px
        style={{ height: "100vh" }}
      >
        <Header />
      </header>
      <main className="max-w-screen-lg mx-auto ">
        <Design />
        <Project />
        <About />
        <Contact />
      </main>
    </>
  );
}
